---
  - name: Install SSH packages
    yum: >
      name={{ item }}
      state=installed
    with_items:
    - openssh
    - openssh-server
    - openssh-clients

  - name: Deploy new /etc/ssh/sshd_config file from template
    template: >
      src=sshd_config.tpl
      dest=/etc/ssh/sshd_config
      owner=root
      group=root
      mode=0400

  - name: Start and enable SSH daemon
    service: >
      name=sshd
      state=started
      enabled=yes
